emulator: "gba"
game: "kirby"
checkpoint_thresholds:
  1: 12
  2: 12
  3: 12
  4: 12
  5: 12
  6: 12
  7: 12
  8: 12
checkpoint_percentages:
  1: 4.8
  2: 13.8 
  3: 20.2
  4: 28.2 
  5: 43.5
  6: 51.6 
  7: 66.6
  8: 100